### ISSUE TITLE
Push to Nuvola Player project

### ISSUE THREAD

**Issue by jrosco** [tiliado/nuvola-app-groove#1]
Hi, Please review my web script for integrating Microsoft Groove music service into the Nuvola Player 

Note: Couldn't extract album info from the website, still looking into this ..

Cheers, 
Joel

**Comment by jiri-janousek** [comment]
Hello @jrosco. I regret to tell you I don't expect to have time for the code review and packaging of your integration script until the release of the stable version of Nuvola Player 3.0, which is due at the end of December 2015. Since the funding of the Nuvola Player project has recently dropped significantly, I cannot spend time on tasks that are not crucial for the stable release. However, the release cycle of web app scripts is not bound to Nuvola Player releases, so I can prepare packages for your script in January 2016 regardless of the development progress and the release date of Nuvola Player 3.1. Thanks for your understanding and patience.

**Comment by jiri-janousek** [comment]
Hello @jrosco. Nuvola Player 3.0.0 Stable is out and I'm going to get around to code reviews in February. There have been [some changes in Service Integration Guidelines and an introduction of Format requirements flags](https://groups.google.com/d/msg/nuvola-player-devel/Eec-MkJJ0cA/C-pyEsL4AQAJ). Could you update your script and ping me when you are done? Thanks!

**Comment by jrosco** [comment]
@fenryxo code committed for new changes 5231c75

**Comment by jiri-janousek** [comment]
Hello @jrosco. Thank for your work. Code looks code, but there are some issue that need to be fixed:
- [x] Remove file `LICENSE-CC-BY.txt` as there is no code with this license.
- [x] `integrate.js:50: Nuvola.config.setDefault(AUTO_PLAY, false)` Also set default value for `MAX_VOLUME`.
- [x] `integrate.js:52-59`: You can remove `Nuvola.core.connect("InitializationForm", this);` and method `WebApp._onInitializationForm = function(emitter, values, entries)` as it's empty.
- [x] `integrate.js:70: entries.push(["header", "Enable autoplay songs on startup"]);`Change header to `Groove Settings`.
- [x] `integrate.js:71: entries.push(["bool", AUTO_PLAY, "AutoPlay"]);` Change label to `Enable autoplay songs on start-up`.
- [x] `integrate.js:74: entries.push(["header", "Set to max volume on startup"]);` Remove this header.
- [x] `integrate.js:75: entries.push(["bool", MAX_VOLUME, "Max Volume"]);` Change label to `Set to maximal volume on start-up`.
- [x] `integrate.js:141`: I'd suggest to [create a ticket](https://github.com/jrosco/nuvola-app-groove/issues/new) about `TODO : Find a way to get artist ablum info`
- [x] [Mark strings in Preferences form for translation](https://tiliado.github.io/nuvolaplayer/development/apps/translations.html)

**Comment by jrosco** [comment]
Hey @fenryxo 

Thanks for the feedback. I have made adjustments as per your request . See 412b18f 

Cheers

**Comment by jiri-janousek** [comment]
Great, @jrosco. I've invited you to [the Tiliado organization](https://github.com/tiliado). It is now necessary to perform final steps:
- [x] [Transfer your repository](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) to the [Nuvola Groove team](https://github.com/orgs/tiliado/teams/nuvola-groove). You will still have commit access and will be the main maintainer of your script. I'll then make a release, Debian/Ubuntu/Fedora packages and announcements.
- [x] Subscribe to [the nuvola-player-devel mailing list]() to be notified about important changes. Don't be afraid of spam, it's a low volume list.
- [x] [Create a Tiliado account](https://tiliado.eu/accounts/signup/) and post your username here. I'll add you to the Tiliado developers group. You can then log in in Nuvola Player to disable donate bar. Also, if you use Debian/Ubuntu/Fedora, you'll have access to Nuvola Player 3.1 Rolling Releases.

**Comment by jrosco** [comment]
Done ... 
Tilido username is **jrosco** 

thanks again, glad to be part of the team :+1:

**Comment by jiri-janousek** [comment]
Account updated, packages published and announced :+1:
