### ISSUE TITLE
ReferenceError: Can't find variable playerInterface

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-groove#5]
From [mailing list](https://groups.google.com/d/msg/nuvola-player-users/0YzDgjla4hE/DIc461s-BwAJ):

>  I am using Groove through the Nuvola player now. It works, but I also get this error message. Anyone knows what it means / do I need to something
![screenshot from 2017-05-11 23-51-27](https://cloud.githubusercontent.com/assets/853706/25989112/3a94125e-36fb-11e7-8585-bd2ce3cf7752.png)

https://github.com/tiliado/nuvola-app-groove/blob/master/integrate.js#L91
> `if (playerInterface.getCurrent())` should be probably replaced with `if (window.playerInterface && playerInterface.getCurrent())`. Or has `playerInterface` gone completely?

@jrosco, could you look at it?

**Comment by jrosco** [comment]
I'll investigate this issue ASAP. Thanks

**Comment by jrosco** [comment]
This has been fixed. I have another issue (#6) to look at and will release this fix when I've fixed #6

**Comment by jiri-janousek** [comment]
2.0 releases. I'll close this issue once I rebuild packages.
