### ISSUE TITLE
RIP Groove

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-groove#8]
Hello @jrosco. Microsoft discontinued Groove Music. Shall we archive this script? Have you migrated to Spotify?

**Comment by jrosco** [comment]
Hi @fenryxo sure lets archive, I started using google music :)

**Comment by jiri-janousek** [comment]
Are you interested in testing Nuvola with Chromium backend? It provides Google Play Music with HTML5 audio playback without Flash plugin.

**Comment by jrosco** [comment]
Yeah sure, happy to test. Point me to the docs and I'll give it a try.

**Comment by jiri-janousek** [comment]
This is the email I sent to Nuvola Premium/Patron users interested in testing:

---

Thanks for your interest in testing Chromium-based Nuvola. The ticket for this port is linked below. Please add a comment there if you find any issue. I'll create a new ticket when deemed necessary.

https://github.com/tiliado/nuvolaruntime/issues/372

Unless you already use Nuvola 4 flatpaks, follow installation instructions to install stable flatpaks: https://nuvola.tiliado.eu/

Run `flatpak remote-list` to find out the name of the Nuvola repository. It may be `eu.tiliado.Nuvola-origin` or `nuvola`. I'll use `eu.tiliado.Nuvola-origin` in following instructions.

Run `flatpak remote-modify --enumerate eu.tiliado.Nuvola-origin` to allow the listing of repository contents, then run `flatpak update && flatpak update --user` to install updates.

Type `flatpak remote-ls eu.tiliado.Nuvola-origin` to list available flatpaks. Choose the script you would like to test and install a development version from the master flatpak branch. For example, type `flatpak install eu.tiliado.Nuvola-origin eu.tiliado.NuvolaAppGooglePlayMusic//master` to install the Google Play Music script.

If both stable and master flatpaks of a particular service are installed, the stable version is the default. You can run the devel version from command line, e.g. `flatpak run eu.tiliado.NuvolaAppGooglePlayMusic//master -D`.

WebKitGTK+ is still the default engine, but some scripts (e.g. Google Play Music and Spotify) use Chromium instead because it is specified in their requirements. If you would like to test a script that uses WebKitGTK by default, launch the flatpak with `NUVOLA_USE_CEF=true`, e.g. `flatpak run --env=NUVOLA_USE_CEF=true eu.tiliado.NuvolaAppAmazonCloudPlayer//master -D`. When the Chromium engine is selected, you will see a warning "Experimental Chromium X.Y.Z engine is in use".

What to focus on:

- Does music playback work?
- Are the web pages loaded and rendered correctly?
- Are the details shown in the developer sidebar correct?
- Do the Nuvola features you usually use work?
- Is there any difference in the responsiveness of the web page between Nuvola/WebKit, Nuvola/Chromium and Google Chrome 63?
- Can you compare memory and CPU usage of Nuvola/WebKit, Nuvola/Chromium and Google Chrome 63?

If there is any issue, please try to reproduce it also with Cefium - a Chromium-based demo web browser, e.g. `flatpak run --command=Cefium eu.tiliado.NuvolaAppGooglePlayMusic//master --url="https://play.google.com/music/" --disable-flash`.

**Comment by jiri-janousek** [comment]
I'm archiving the repo. Should you have any comments about the Chromium port, use tiliado/nuvolaruntime#372
